CourseSite/CourseSite/Models/DAL/Instractors.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSite.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Instractors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instractors()
        {
            this.Course_Instractors = new HashSet<Course_Instractors>();
        }

        public int ID { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_EngName")]
        [Required(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledISRequired")]
        [MaxLength(200, ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledMaxLengtt")]
        public string Instractor_EngName { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_AraName")]
        [Required(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledISRequired")]
        [MaxLength(200, ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledMaxLengtt")]
        public string Instractor_AraName { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_Address")]
        [MaxLength(500, ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledMaxLengtt")]
        public string Instractor_Address { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_Mobile")]
        [Phone(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "InvalidMobileNumber")]
        [Required(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledISRequired")]
        public string Instractor_Mobile { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_phone")]
        public string Instractor_phone { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_Email")]

        [EmailAddress(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "InvalidEmailAddress")]
        [Required(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledISRequired")]
        public string Instractor_Email { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_Status")]
        [Required(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledISRequired")]
        public Nullable<int> Instractor_StatusID { get; set; }

        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_Gender")]
        [Required(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledISRequired")]
        public Nullable<int> Instractor_GenderID { get; set; }

        [DataType(DataType.DateTime)]
        [UIHint("_DateTime")]
        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Instractors), Name = "Instractor_Birthdate")]
        public Nullable<System.DateTime> Instractor_Birthdate { get; set; }


        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Main), Name = "Facebook")]
        public string Instractor_Facebook { get; set; }
        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Main), Name = "linkedIn")]
        public string Instractor_LinkedIn { get; set; }
        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Main), Name = "Twitter")]
        public string instractor_twitter { get; set; }
        [Display(ResourceType = typeof(CourseSite.App_GlobalResources.Main), Name = "ImagePath")]
        public string instractor_imagePath { get; set; }
        public HttpPostedFileBase ImageUpload { get; set; }

        public string instractor_QualificationsAra { get; set; }

        [Display(Name = "English Qualifications")]
        [Required(ErrorMessageResourceType = typeof(CourseSite.App_GlobalResources.Instractors), ErrorMessageResourceName = "FiledISRequired")]
        public string instractor_QualificationsEnglish { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Instractors> Course_Instractors { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual InstractorStatus InstractorStatus { get; set; }

    }
}

CourseSite/CourseSite/Controllers/InstractorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseSite.Models.DAL;
using CourseSite.Models;
using CourseSite.Common;
using System.IO;

namespace CourseSite.Controllers
{
    public class InstractorController : Controller
    {

        // GET: Instractor
        public ActionResult Index()
        {
            // var instractors = db.Instractors.Include(i => i.Gender).Include(i => i.InstractorStatus);
            using (CenterDBEntities db = new CenterDBEntities())
            {
                var query = db.Instractors.ToList();
                return View(query);
            }


            //return View(instractors.ToList());
        }
        public ActionResult Main()
        {
            using (CenterDBEntities db = new CenterDBEntities())
            {
                var query = db.Instractors.ToList();
                return View(query);
            }
        }
        // GET: Instractor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (CenterDBEntities db = new CenterDBEntities())
            {
                Instractors instractors = db.Instractors.Include("InstractorStatus").Include("Gender").SingleOrDefault(x => x.ID == id.Value);

                if (instractors == null)
                {
                    return HttpNotFound();
                }
                return View(instractors);
            }
        }

        // GET: Instractor/Create
        public ActionResult Create()
        {

            ViewBag.Instractor_GenderID = UImanger.GenderDll();
            ViewBag.Instractor_StatusID = InstractorsRoutines.GetInstractorStatusDLL();
            return View();
        }

        // POST: Instractor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Instractor_EngName,Instractor_AraName,instractor_imagePath,,ImageUpload,Instractor_Address,Instractor_Mobile," + "Instractor_phone,Instractor_Email,Instractor_Facebook,instractor_twitter,Instractor_LinkedIn,Instractor_StatusID,Instractor_GenderID,Instractor_Birthdate,instractor_QualificationsEnglish")] Instractors instractors)
        {
            if (ModelState.IsValid)
            {
                using (CenterDBEntities db = new CenterDBEntities())
                {
                    db.Instractors.Add(instractors);
                    db.SaveChanges();
                    if (instractors.ImageUpload != null && !string.IsNullOrEmpty(instractors.ImageUpload.FileName))
                    {
                        string subPath = "~/Uploads/Photo/instractors/";
                        var filename = Path.GetFileName(instractors.ImageUpload.FileName);
                        var formattedFileName = string.Format("{0}-{1}{2}"
                                                       , instractors.Instractor_EngName
                                                       , instractors.ID
                                                       , Path.GetExtension(filename));
                        bool exists = System.IO.Directory.Exists(subPath);

                        if (!exists)
                            System.IO.Directory.CreateDirectory(Server.MapPath("~/Uploads/Photo/instractors/"));
                        subPath = Path.Combine("~/Uploads/Photo/instractors/", formattedFileName);
                        var path = Server.MapPath(subPath);
                        instractors.ImageUpload.SaveAs(path);
                        instractors.instractor_imagePath = subPath;

                        db.Entry(instractors).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Instractor_GenderID = UImanger.GenderDll();
            ViewBag.Instractor_StatusID = InstractorsRoutines.GetInstractorStatusDLL();
            return View(instractors);
        }

        // GET: Instractor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (CenterDBEntities db = new CenterDBEntities())
            {
                Instractors instractors = db.Instractors.Find(id);
               
                if (instractors == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Instractor_GenderID = UImanger.GenderDll();
                ViewBag.Instractor_StatusID = InstractorsRoutines.GetInstractorStatusDLL();
                return View(instractors);
            }
        }

        // POST: Instractor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Instractor_EngName,Instractor_AraName,instractor_imagePath,,ImageUpload,Instractor_Address,Instractor_Mobile," + "Instractor_phone,Instractor_Email,Instractor_Facebook,instractor_twitter,Instractor_LinkedIn,Instractor_StatusID,Instractor_GenderID,Instractor_Birthdate,instractor_QualificationsEnglish")] Instractors instractors)
        {
            if (ModelState.IsValid)
            {
                string oldimagepath = "";
                using (CenterDBEntities db = new CenterDBEntities())
                {
                    oldimagepath=db.Instractors.Where(x => x.ID == instractors.ID).SingleOrDefault().instractor_imagePath;
                }
                    using (CenterDBEntities db = new CenterDBEntities())
                {
                    if (instractors.ImageUpload != null && !string.IsNullOrEmpty(instractors.ImageUpload.FileName))
                    {
                        string subPath = "~/Uploads/Photo/instractors/";
                        var filename = Path.GetFileName(instractors.ImageUpload.FileName);
                        var formattedFileName = string.Format("{0}-{1}{2}"
                                                       , instractors.Instractor_EngName
                                                       , instractors.ID
                                                       , Path.GetExtension(filename));
                        bool exists = System.IO.Directory.Exists(subPath);

                        if (!exists)
                            System.IO.Directory.CreateDirectory(Server.MapPath("~/Uploads/Photo/instractors/"));
                        subPath = Path.Combine("~/Uploads/Photo/instractors/", formattedFileName);
                        var path = Server.MapPath(subPath);
                        instractors.ImageUpload.SaveAs(path);
                        instractors.instractor_imagePath = subPath;                        
                    }
                    else
                    {

                        instractors.instractor_imagePath = oldimagepath;
                    }
                    db.Entry(instractors).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Instractor_GenderID = UImanger.GenderDll();
            ViewBag.Instractor_StatusID = InstractorsRoutines.GetInstractorStatusDLL();
            return View(instractors);
        }

        public ActionResult DeleteConfirmed(int id)
        {
            using (CenterDBEntities db = new CenterDBEntities())
            {
                Instractors instractors = db.Instractors.Find(id);
                db.Instractors.Remove(instractors);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                using (CenterDBEntities db = new CenterDBEntities())
                {
                    db.Dispose();
                }
            }
            base.Dispose(disposing);
        }
    }
}

CourseSite/CourseSite/Views/Instractor/Create.cshtml
@model CourseSite.Models.DAL.Instractors

@{

    ViewBag.Title = Resources.Main.Create +" "+Resources.Cutomers.Cutomer;

    ViewBag.Title = Resources.Main.Create +" "+Resources.Instractors.InstractorsTitle;
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@Resources.Instractors.InstractorsTitle</h2>

@using (Html.BeginForm("Create", "Instractor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Resources.Main.Create @Resources.Instractors.InstractorsTitle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-4 col-md-push-8 text-center">
                <div class="form-group">
                    <span id="previewPane">
                        <img class="upload" onchange="readURL(this);" name="file" id="img_prev" src="~/Uploads/Gallary/defaultcourse.jpg" alt="your image"
                             style="width:250px;height:250px">
                    </span>
                </div>
            </div>
            <div class="col-md-8 col-md-pull-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_EngName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_EngName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_EngName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_AraName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_AraName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_AraName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.instractor_imagePath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.ImageUpload, new { type = "file", id = "file", name = "file", onchange = "readURL(this);" })
                        @Html.ValidationMessageFor(model => model.instractor_imagePath, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_Mobile, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_Mobile, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_Facebook, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_Facebook, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_Facebook, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.instractor_twitter, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.instractor_twitter, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.instractor_twitter, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_LinkedIn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_LinkedIn, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_LinkedIn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_StatusID, Resources.Instractors.Instractor_Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Instractor_StatusID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Instractor_StatusID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_GenderID, Resources.Instractors.Instractor_Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Instractor_GenderID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Instractor_GenderID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_Birthdate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Instractor_Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Instractor_Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Instractor_Birthdate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.instractor_QualificationsEnglish, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.instractor_QualificationsEnglish, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.instractor_QualificationsEnglish, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value='@Resources.Main.Create' class="btn btn-default" />
                </div>
            </div>
        </div>
        </div>
    
}

<div>
    @Html.ActionLink(Resources.Main.BTL, "Index")
</div>



<script>

            var blank = "http://upload.wikimedia.org/wikipedia/commons/c/c0/Blank.gif";

            function readURL(input) {

                if (input.files && input.files[0]) {

                    var reader = new FileReader();
                    reader.onload = function (e) {

                        $('#img_prev')

                            .attr('src', e.target.result)

                            .height(200);

                    };
                    reader.readAsDataURL(input.files[0]);

                }

                else {

                    var img = input.value;

                    $('#img_prev').attr('src', img).height(200);

                }

                $("#x").show().css("margin-right", "10px");

            }

            $(document).ready(function () {

                $("#x").click(function () {

                    $("#img_prev").attr("src", blank);

                    $("#x").hide();

                });

            });
</script>
<style type="text/css">
    .fileUpload {
        position: relative;
        overflow: hidden;
        margin: 10px;
    }

        .fileUpload input.upload {
            position: absolute;
            top: 0;
            right: 0;
            margin: 0;
            padding: 0;
            font-size: 20px;
            cursor: pointer;
            opacity: 0;
            filter: alpha(opacity=0);
        }

    .field-validation-error {
        color: #a94442;
    }
</style>

CourseSite/CourseSite/Views/Instractor/Delete.cshtml
@model CourseSite.Models.DAL.Instractors

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instractors</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instractor_EngName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_EngName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_AraName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_AraName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender.Gender_EngName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender.Gender_EngName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstractorStatus.Status_EngName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstractorStatus.Status_EngName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CourseSite/CourseSite/Views/Instractor/Details.cshtml
@model CourseSite.Models.DAL.Instractors

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Instractors</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instractor_EngName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_EngName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_AraName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_AraName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Email)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Facebook)
        </dt>

        <dd>            
            <a href="@Html.DisplayFor(model => model.Instractor_Facebook)" target="_blank">@Html.DisplayFor(model => model.Instractor_Facebook)</a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.instractor_twitter)
        </dt>

        <dd>
            <a href="@Html.DisplayFor(model => model.instractor_twitter)" target="_blank">  @Html.DisplayFor(model => model.instractor_twitter)</a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instractor_LinkedIn)
        </dt>

        <dd>
            <a href="@Html.DisplayFor(model => model.Instractor_LinkedIn)" target="_blank" > @Html.DisplayFor(model => model.Instractor_LinkedIn)</a>
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Instractor_Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instractor_Birthdate)
        </dd>

        <dt>
            @Resources.Instractors.Instractor_Status
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender.Gender_EngName)
        </dd>

        <dt>
            @Resources.Instractors.Instractor_Gender
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstractorStatus.Status_EngName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(Resources.Main.Edit, "Edit", new { id = Model.ID }) |
    @Html.ActionLink(Resources.Main.BTL, "Index")
</p>

CourseSite/CourseSite/Views/Instractor/InstractorPMView.cshtml
@model IEnumerable<CourseSite.Models.DAL.Instractors>

@foreach (var item in Model)
{
    <div class="col-lg-4 col-md-6">
        <div class="speaker">
           @if (!string.IsNullOrEmpty(item.instractor_imagePath))
           {
            <img src="@Url.Content(item.instractor_imagePath)" alt="Speaker 1" class="img-fluid">
           }
           else
           {
            <img src="~/assets/img/speakers/ereny.jpg" alt="Speaker 2" class="img-fluid">
           }
            <div class="details">
                <h3>
                    <a href="speaker-details.html">
                        @if (CourseSite.Common.UImanger.CurrentLang != "en")
                {
                            @item.Instractor_AraName
                        }
                        else
                        {
                            @item.Instractor_EngName
                        }
                    </a>
                </h3>
                @*<p>@item.</p>*@
                <div class="social">
                    <a href="@item.instractor_twitter"><i class="fa fa-twitter"></i></a>
                    <a href="@item.Instractor_Facebook"><i class="fa fa-facebook"></i></a>
                    @*<a href=""><i class="fa fa-google-plus"></i></a>*@
                    <a href="@item.Instractor_LinkedIn"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
        </div>
    </div>
}